### ISSUE TITLE
Files are deployed in subfolder after repo reconfiguration, not processing gulpfile

### ISSUE THREAD

**Issue by nickbasham-grayloon** [linchpin/wpengine-codeship-continuous-deployment#6]
First off, thanks for all the work on this script, it's been really useful for my development process on a big project.

So here's my scenario and the problem I'm running into. I started a project on WP Engine by setting up a development environment and pulling it down via git. Starting out, I worked in a master branch configured to target the development environment and the build/deploy script was working great.

Now that I'm ready for deployment, I created a staging branch, set up a staging environment and configured the environment variables. Deploying that worked flawlessly. I did an environment copy in WP Engine to migrate it to production and so the site's live now.

Now I'm ready to set up the repo with master, staging and develop branches. I change the WPE_INSTALL_DEV variable to the subdomain of the develop environment, add the build-deploy deployment script for a develop branch, and then git push. The script runs and completes, but now I'm running into two issues:

1. It says it can't find my gulpfile, which hasn't moved and has been processed correctly on every push until now, and 
2. All files have gotten moved into a subfolder of the theme, ie. wp-content/themes/[theme]/wp-content/themes/[theme]

I then triggered another deploy using the #force hashtag, thinking that might fix it, but the same thing occurred. Can't find the gulpfile and all files placed within the theme folder.

Any ideas what's going on? Any help would be greatly appreciated, thanks!

**Comment by aaronware** [comment]
Hey @nickbasham-grayloon glad it's worked for you for the most part. Traditionally, how we have used this deployment process for @Linchpin projects in the past is that your `REPO_NAME` and the `PROJECT_TYPE` directly define what subfolder your project would be deployed to `PROJECT_TYPE/REPO_NAME`, is `themes/nicks-awesome-theme`. Previously instead of 1 monolithic repo, we would have numerous projects that all deployed individually to WP Engine. Does your repo contain just the theme or is your project an all-encompassing project including core? Or "wp-content"? 

If you're on GitHub and want to look at actions we have a ton of other projects that allow for deployment of individual themes and plugins or using wp-content as the base of your .git project and deploying all themes and plugins to that.

**Comment by aaronware** [comment]
Useful Actions:
https://github.com/linchpin/action-wpengine-deploy
https://github.com/linchpin?q=action 👈🏻 All of our actions (mainly around deployments).

**Comment by nickbasham-grayloon** [comment]
Hey @aaronware, thanks for the quick reply!

It's one repo with composer managing plugins and core, and the theme. I need to look at the script a bit closer, but I think what was happening is that the script code path was running via the legacy route when I was using only a master branch pointed to one environment, which was deploying to root instead of the theme subfolder. Now that I switched to master/staging/develop branches, it much set to deploying within the theme.

Not sure if you're interested in making any tweaks to the script, but one thought would be to add a `PROJECT_TYPE = site` environment variable to deploy to root instead of the theme or plugin directories.

Didn't realize you had other deployment actions, I'll definitely take a look. Between those and this current script, I'm sure I'll be able to make the tweaks I need to get deployments back up and running. 

Thanks again and have a great weekend!

**Comment by aaronware** [comment]
@nickbasham-grayloon I am not opposed to that sorta change. We don't really use this process anymore as we moved on from CodeShip. But if you want to make the adjustment in a pull request, I can definitely review it and give it a test.
